server:
  port: 8191

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sasankaviraj/spring-cloud-config-store
          search-paths:
            - '*service'  # *service --> start with anything but end with service
  application:
    name: cloud-config-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
