security:
  oauth2:
    client:
      client-id: mobile
      client-secret: pin
      user-authorization-uri: http://localhost:9193/oauth/authorize
      access-token-uri: http://localhost:9193/oauth/token
    resource:
      token-info-uri: http://localhost:9193/oauth/check_token #to validate token

server:
  servlet:
    session:
      cookie:
        name: KSESSION  #mechanism to store the token get from auth server
